name: athena
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  google_fonts: ^4.0.1
  flutter_riverpod: ^2.1.1
  share_plus: ^6.3.0
  html: ^0.15.1
  cached_network_image: ^3.2.3
  palette_generator: ^0.3.3+2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  rounded_loading_button: ^2.1.0
  file_picker: ^5.2.4
  path_provider: ^2.0.11
  epubx: ^3.0.0
  image: ^3.1.3
  flutter_inappwebview: ^5.7.2+3
  octo_image: ^1.0.2
  collection: ^1.17.0
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/icon.png"
  min_sdk_android: 26
